### ISSUE TITLE
[BUG] Failed to compile Can't resolve 'worker_threads'

### ISSUE THREAD

**Issue by vwebtech** [VincentJonathan/scrape-yt#19] opened 2020-10-16 17:27 UTC
Got this issue 

trying to use it on nodejs app

Failed to compile
./node_modules/scrape-yt/dist/index.js
Module not found: Can't resolve 'worker_threads' in '\node_modules\scrape-yt\dist'

**Comment by SuspiciousLookingOwl** [comment] 2020-10-16 17:29
Can you provide a reproducible code?

**Comment by SuspiciousLookingOwl** [comment] 2020-10-16 17:32
This seems to be caused by an incompatible Node version, what Node version are you using?

**Comment by Fanna1119** [comment] 2020-10-25 18:02
Also having this issue. Node v14.12.0

**Comment by SuspiciousLookingOwl** [comment] 2020-10-25 18:38
I'm still not sure what causes this, you can try the beta version (`npm i scrape-yt@beta`) but I don't think you will able to use `useWorkerThread` option if you need it.

I tried it on Node v14.12.0 using nvm on WSL, and it didn't gave me any error.

**Comment by SuspiciousLookingOwl** [comment] 2020-11-13 10:35
Closing this now as a27991f2370906c43ddf518d3875ec47d927e04e should've fixed this. Also published the update on version `1.4.5`.

If this still persists, feel free to re-open the issue.

**Closed as completed by SuspiciousLookingOwl** 2020-11-13 10:35 UTC
